name: 'Review Assign Action'
description: 'Automatically set assignees and reviewers on pull requests.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'users'
  color: 'white'
inputs:
  assignees:
    description: ''
    required: false
  bot-accounts:
    description: ''
    required: false
  reviewers:
    description: ''
    required: false
  max-num-of-reviewers:
    description: ''
    required: false
  draft-keyword:
    description: ''
    required: false
  ready-comment:
    description: ''
    required: false
  merged-comment:
    description: ''
    required: false
  github-token:
    description: ''
    default: ${{ github.token }}
    required: false
  event:
    description: ''
    default: ${{ toJson(github.event) }}
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node12'
  main: 'dist/index.js'
